name: Build Flipper App

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Flipper Zero toolchain
      run: |
        git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
        cd flipperzero-firmware
        ./fbt applications_user
        cp build/f7-firmware-D/.extapps/*.fap ../
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: bluetooth_spammer
        path: "*.fap"
